---
title: "Latent Variable Modeling"
author: "Jon Lefcheck"
date: "November 13, 2018"
output: html_document
---

## 1.1 Introduction to Latent Variable Modeling

*Latent variables* are variables that are unobserved, but whose influence can be summarized through one or more *indicator variables*. They are useful for capturing complex or conceptual properties of a system that are difficult to quantify or measure directly. Early applications of latent variables, for example, focused on modeling the effects of 'general intelligence,' which is an abstract concept that is impossible to measure, but can be approximated using scores from different tests of cognitive performance (e.g., memory, verbal, spatial, etc.).

Consider the following simple example of a latent variable:



For the moment, latent variables are restricted to covariance-based SEM, although we are working to extend some concepts using the piecewise framework.

## 1.2 Latent Variables as Exogenous in *lavaan*

## 1.3 Latent Variables as Endogenous in *lavaan*