--- 
title: "Structural Equation Modeling in R for Ecology and Evolution"
author: "Jonathan Lefcheck"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a free resource"
---

Structural equation modeling is among the fastest growing statistical techniques in the natural sciences, thanks in large part to new advances and software packages that make it broadly applicable and easy to use.

This book is meant to be an approachable guide to the theory, math, and application of SEM. It integrates code from popular open-source packages such as *lavaan* and *piecewiseSEM*. Each chapter ends with worked examples from the published literature.

Moreover, as the author of the *piecewiseSEM* package, this format allows me to document newly-deployed functionality in the package, such as the addition of multigroup analysis and composite variables, new forms of standardization, and updates to model R<sup>2</sup>s.

In some ways, this is my grandest experiment: happy reading!